name: Build Project

on:
  - push
  - pull_request

jobs:
  windows:
    name: Windows Server 2022
    runs-on: windows-2022
    steps:
      - name: GitHub repository checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure and Build sources
        run: |
          mkdir build && cd build && cmake .. && cd ..
          cmake --build build --config Release

  ubuntu:
    name: Ubuntu 20.04
    runs-on: ubuntu-20.04
    steps:
      - name: GitHub repository checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure and Build sources
        run: |
          mkdir -p build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release && cd ..
          cmake --build build --config Release

  macos:
    name: macOS Big Sur 11
    runs-on: macos-11
    steps:
      - name: Set up environment
        run: brew install coreutils
      - name: GitHub repository checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure and Build sources
        run: |
          mkdir -p build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release && cd ..
          cmake --build build --config Release
